# Modelo de datos - 3ra entrega

## Denisse Gonzalez Carmona

# Librerias

In [1]:
import requests
import json
import pandas as pd
import warnings
warnings.filterwarnings('ignore') #Hacemos esto para omitir los warnings

##  Tabla Drivers

Primero haremos nuestro diccionario de listas, llamado drivers.

In [2]:
drivers={'year':[],
        'id': [],
        'permanentNumber':[],
        'code':[],
        'url':[],
        'givenName':[],
        'familyName':[],
        'dob':[],
        'nationality':[],
        }

Haremos un for para tener las carreras del 2022. Lo que tiene que cambiar es el url donde piden los años
NOTA:
Ponemos {} para señalar que es una variable aleatoria y va cambiando.

In [3]:
for year in list(range(2010,2023)):    
    url = 'http://ergast.com/api/f1/{}/drivers.json'
    response = requests.get(url.format(year))
    content=json.loads(response.content)

    for item in content['MRData']['DriverTable']['Drivers']:
        drivers['year'].append(year)
        drivers['id'].append(item['driverId'])
        drivers['code'].append(item['code'])
        drivers['url'].append(item['url'])
        drivers['givenName'].append(item['givenName'])
        drivers['familyName'].append(item['familyName'])
        drivers['dob'].append(item['dateOfBirth'])
        drivers['nationality'].append(item['nationality'])
        try:
            drivers['permanentNumber'].append(item['permanentNumber'])
        except:
            drivers['permanentNumber'].append(None)

## Data frame Drivers

In [4]:
pd.DataFrame(drivers)

,year,id,permanentNumber,code,url,givenName,familyName,dob,nationality
0,2010,alguersuari,None,ALG,http://en.wikipedia.org/wiki/Jaime_Alguersuari,Jaime,Alguersuari,1990-03-23,Spanish
1,2010,alonso,14,ALO,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando,Alonso,1981-07-29,Spanish
2,2010,barrichello,None,BAR,http://en.wikipedia.org/wiki/Rubens_Barrichello,Rubens,Barrichello,1972-05-23,Brazilian
3,2010,buemi,None,BUE,http://en.wikipedia.org/wiki/S%C3%A9bastien_Buemi,Sébastien,Buemi,1988-10-31,Swiss
4,2010,button,22,BUT,http://en.wikipedia.org/wiki/Jenson_Button,Jenson,Button,1980-01-19,British
...,...,...,...,...,...,...,...,...,...
299,2022,stroll,18,STR,http://en.wikipedia.org/wiki/Lance_Stroll,Lance,Stroll,1998-10-29,Canadian
300,2022,tsunoda,22,TSU,http://en.wikipedia.org/wiki/Yuki_Tsunoda,Yuki,Tsunoda,2000-05-11,Japanese
301,2022,max_verstappen,33,VER,http://en.wikipedia.org/wiki/Max_Verstappen,Max,Verstappen,1997-09-30,Dutch
302,2022,vettel,5,VET,http://en.wikipedia.org/wiki/Sebastian_Vettel,Sebastian,Vettel,1987-07-03,German
303,2022,zhou,24,ZHO,http://en.wikipedia.org/wiki/Guanyu_Zhou,Guanyu,Zhou,1999-05-30,Chinese

Luego lo vamos a exportar en un archivo csv.

In [5]:
pd.DataFrame(drivers).to_csv('drivers.csv',index=False)

# Tabla  Constructors

Primero haremos nuestro diccionario de listas, llamado constructors.

In [6]:
constructors={'year':[],
             'constructorId':[],
             'url':[],
             'name':[],
             'nationality':[]}

Creamos el ciclo for para los años 2010 a 2022.

In [7]:
for year in list(range(2010,2023)):
    url = 'http://ergast.com/api/f1/{}/constructors.json'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    
    for item in content['MRData']['ConstructorTable']['Constructors']:
        constructors['year'].append(year)
        constructors['constructorId'].append(item['constructorId'])
        constructors['url'].append(item['url'])
        constructors['name'].append(item['name'])
        constructors['nationality'].append(item['nationality'])

## Data Frame Constuctors

In [8]:
pd.DataFrame(constructors)

,year,constructorId,url,name,nationality
0,2010,ferrari,http://en.wikipedia.org/wiki/Scuderia_Ferrari,Ferrari,Italian
1,2010,force_india,http://en.wikipedia.org/wiki/Racing_Point_Forc...,Force India,Indian
2,2010,hrt,http://en.wikipedia.org/wiki/Hispania_Racing,HRT,Spanish
3,2010,lotus_racing,http://en.wikipedia.org/wiki/Lotus_Racing,Lotus,Malaysian
4,2010,mclaren,http://en.wikipedia.org/wiki/McLaren,McLaren,British
...,...,...,...,...,...
134,2022,haas,http://en.wikipedia.org/wiki/Haas_F1_Team,Haas F1 Team,American
135,2022,mclaren,http://en.wikipedia.org/wiki/McLaren,McLaren,British
136,2022,mercedes,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...,Mercedes,German
137,2022,red_bull,http://en.wikipedia.org/wiki/Red_Bull_Racing,Red Bull,Austrian
138,2022,williams,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,Williams,British

Lo exportarmos en un archivo csv.

In [10]:
pd.DataFrame(constructors).to_csv('constructors.csv',index=False)

##  Tabla Circuits

Primero haremos nuestro diccionario de listas, llamado circuits

In [11]:
circuits = {'year':[],
           'id':[],
           'url':[],
           'circuitName':[],
           'lat':[],
           'long':[],
           'locality':[],
           'country':[]}

Creamos el ciclo for para los años 2010 a 2022.

In [12]:
for year in list(range(2010,2023)):
    url = 'http://ergast.com/api/f1/{}/circuits.json'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    
    for item in content['MRData']['CircuitTable']['Circuits']:
        circuits['year'].append(year)
        circuits['id'].append(item['circuitId'])
        circuits['url'].append(item['url'])
        circuits['circuitName'].append(item['circuitName'])
        circuits['lat'].append(item['Location']['lat'])
        circuits['long'].append(item['Location']['long'])
        circuits['locality'].append(item['Location']['locality'])
        circuits['country'].append(item['Location']['country'])

# Data Frame Circuits

In [13]:
pd.DataFrame(circuits)

,year,id,url,circuitName,lat,long,locality,country
0,2010,albert_park,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,Albert Park Grand Prix Circuit,-37.8497,144.968,Melbourne,Australia
1,2010,bahrain,http://en.wikipedia.org/wiki/Bahrain_Internati...,Bahrain International Circuit,26.0325,50.5106,Sakhir,Bahrain
2,2010,catalunya,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,Circuit de Barcelona-Catalunya,41.57,2.26111,Montmeló,Spain
3,2010,hockenheimring,http://en.wikipedia.org/wiki/Hockenheimring,Hockenheimring,49.3278,8.56583,Hockenheim,Germany
4,2010,hungaroring,http://en.wikipedia.org/wiki/Hungaroring,Hungaroring,47.5789,19.2486,Budapest,Hungary
...,...,...,...,...,...,...,...,...
250,2022,spa,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...,Circuit de Spa-Francorchamps,50.4372,5.97139,Spa,Belgium
251,2022,suzuka,http://en.wikipedia.org/wiki/Suzuka_Circuit,Suzuka Circuit,34.8431,136.541,Suzuka,Japan
252,2022,villeneuve,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...,Circuit Gilles Villeneuve,45.5,-73.5228,Montreal,Canada
253,2022,yas_marina,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,Yas Marina Circuit,24.4672,54.6031,Abu Dhabi,UAE
254,2022,zandvoort,http://en.wikipedia.org/wiki/Circuit_Zandvoort,Circuit Park Zandvoort,52.3888,4.54092,Zandvoort,Netherlands

Lo exportarmos en un archivo csv.

In [15]:
pd.DataFrame(circuits).to_csv('circuits.csv',index=False)

## Tabla  Qualifying

Primero haremos nuestro diccionario de listas, llamado  qualifying

In [16]:
qualifying = {'year':[],
            'number':[],
            'position':[],
            'driverId': [],
            'permanentNumber':[],
            'code':[],
            'urlD':[],
            'givenName':[],
            'familyName':[],
            'dob':[],
            'nationality':[],
            'constructorId':[],
            'urlC':[],
            'name':[],
            'nationalityC':[],
            'Q1':[],
            'Q2':[],
            'Q3':[]}

Creamos el ciclo for para los años 2010 a 2022.

In [17]:
for year in list(range(2010,2023)):    
    url = 'http://ergast.com/api/f1/{}/qualifying.json'
    response = requests.get(url.format(year))
    content=json.loads(response.content)

    for item in content['MRData']['RaceTable']['Races'][0]['QualifyingResults']:
        qualifying['year'].append(year)
        try:
            qualifying['number'].append(item['number'])
        except:
            qualifying['number'].append(None)
        qualifying['position'].append(item['position'])
        qualifying['driverId'].append(item['Driver']['driverId'])
        try:
            qualifying['permanentNumber'].append(item['Driver']['permanentNumber'])
        except:
            qualifying['permanentNumber'].append(None)
        qualifying['code'].append(item['Driver']['code'])
        qualifying['urlD'].append(item['Driver']['url'])
        qualifying['givenName'].append(item['Driver']['givenName'])
        qualifying['familyName'].append(item['Driver']['familyName'])
        qualifying['dob'].append(item['Driver']['dateOfBirth'])
        qualifying['nationality'].append(item['Driver']['nationality'])
        qualifying['constructorId'].append(item['Constructor']['constructorId'])
        qualifying['urlC'].append(item['Constructor']['url'])
        qualifying['name'].append(item['Constructor']['name'])
        qualifying['nationalityC'].append(item['Constructor']['nationality'])
        try:
            qualifying['Q1'].append(item['Q1'])
        except:
            qualifying['Q1'].append(None)
        try:
            qualifying['Q2'].append(item['Q2'])
        except:
            qualifying['Q2'].append(None)
        try:
            qualifying['Q3'].append(item['Q3'])
        except:
            qualifying['Q3'].append(None)

    for item in content['MRData']['RaceTable']['Races'][1]['QualifyingResults']:
        qualifying['year'].append(year)
        try:
            qualifying['number'].append(item['number'])
        except:
            qualifying['number'].append(None)
        qualifying['position'].append(item['position'])
        qualifying['driverId'].append(item['Driver']['driverId'])
        try:
            qualifying['permanentNumber'].append(item['Driver']['permanentNumber'])
        except:
            qualifying['permanentNumber'].append(None)
        qualifying['code'].append(item['Driver']['code'])
        qualifying['urlD'].append(item['Driver']['url'])
        qualifying['givenName'].append(item['Driver']['givenName'])
        qualifying['familyName'].append(item['Driver']['familyName'])
        qualifying['dob'].append(item['Driver']['dateOfBirth'])
        qualifying['nationality'].append(item['Driver']['nationality'])
        qualifying['constructorId'].append(item['Constructor']['constructorId'])
        qualifying['urlC'].append(item['Constructor']['url'])
        qualifying['name'].append(item['Constructor']['name'])
        qualifying['nationalityC'].append(item['Constructor']['nationality'])
        try:
            qualifying['Q1'].append(item['Q1'])
        except:
            qualifying['Q1'].append(None)
        try:
            qualifying['Q2'].append(item['Q2'])
        except:
            qualifying['Q2'].append(None)
        try:
            qualifying['Q3'].append(item['Q3'])
        except:
            qualifying['Q3'].append(None)

## Data Frame Qualifying

In [18]:
pd.DataFrame(qualifying)

,year,number,position,driverId,permanentNumber,code,urlD,givenName,familyName,dob,nationality,constructorId,urlC,name,nationalityC,Q1,Q2,Q3
0,2010,5,1,vettel,5,VET,http://en.wikipedia.org/wiki/Sebastian_Vettel,Sebastian,Vettel,1987-07-03,German,red_bull,http://en.wikipedia.org/wiki/Red_Bull_Racing,Red Bull,Austrian,1:55.029,1:53.883,1:54.101
1,2010,7,2,massa,19,MAS,http://en.wikipedia.org/wiki/Felipe_Massa,Felipe,Massa,1981-04-25,Brazilian,ferrari,http://en.wikipedia.org/wiki/Scuderia_Ferrari,Ferrari,Italian,1:55.313,1:54.331,1:54.242
2,2010,8,3,alonso,14,ALO,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando,Alonso,1981-07-29,Spanish,ferrari,http://en.wikipedia.org/wiki/Scuderia_Ferrari,Ferrari,Italian,1:54.612,1:54.172,1:54.608
3,2010,2,4,hamilton,44,HAM,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis,Hamilton,1985-01-07,British,mclaren,http://en.wikipedia.org/wiki/McLaren,McLaren,British,1:55.341,1:54.707,1:55.217
4,2010,4,5,rosberg,6,ROS,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico,Rosberg,1985-06-27,German,mercedes,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...,Mercedes,German,1:55.463,1:54.682,1:55.241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,2022,63,6,russell,63,RUS,http://en.wikipedia.org/wiki/George_Russell_%2...,George,Russell,1998-02-15,British,mercedes,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...,Mercedes,German,1:29.680,1:29.618,1:29.104
386,2022,14,7,alonso,14,ALO,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando,Alonso,1981-07-29,Spanish,alpine,http://en.wikipedia.org/wiki/Alpine_F1_Team,Alpine F1 Team,French,1:29.978,1:29.295,1:29.147
387,2022,77,8,bottas,77,BOT,http://en.wikipedia.org/wiki/Valtteri_Bottas,Valtteri,Bottas,1989-08-28,Finnish,alfa,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Alfa Romeo,Swiss,1:29.683,1:29.404,1:29.183
388,2022,10,9,gasly,10,GAS,http://en.wikipedia.org/wiki/Pierre_Gasly,Pierre,Gasly,1996-02-07,French,alphatauri,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,AlphaTauri,Italian,1:29.891,1:29.418,1:29.254
389,2022,20,10,kevin_magnussen,20,MAG,http://en.wikipedia.org/wiki/Kevin_Magnussen,Kevin,Magnussen,1992-10-05,Danish,haas,http://en.wikipedia.org/wiki/Haas_F1_Team,Haas F1 Team,American,1:29.831,1:29.546,1:29.588

Lo exportarmos en un archivo csv.

In [19]:
pd.DataFrame(qualifying).to_csv("qualifying.csv", index = False )

## Seasons

Para Season trabajaremos analogamente, la unica diferencia es que definiremos el url que ulitizamos con un limite de datos. Como se muestra a continuacion.

In [20]:
url='https://ergast.com/api/f1/seasons.json?limit=74'
response = requests.get(url.format())
content=json.loads(response.content)

Creamos nuestro diccionario de listas, llamado seasons

In [21]:
seasons ={'season':[],'url':[]}

Creamos nuestro ciclo for, para agregar la informacion de nuestras temporadas.

In [22]:
for item in content['MRData']['SeasonTable']['Seasons']:
    seasons['season'].append(int(item['season']))
    seasons['url'].append(item['url'])

## Data Frame Seasons

In [23]:
pd.DataFrame(seasons)

    season                                                url
0     1950  http://en.wikipedia.org/wiki/1950_Formula_One_...
1     1951  http://en.wikipedia.org/wiki/1951_Formula_One_...
2     1952  http://en.wikipedia.org/wiki/1952_Formula_One_...
3     1953  http://en.wikipedia.org/wiki/1953_Formula_One_...
4     1954  http://en.wikipedia.org/wiki/1954_Formula_One_...
..     ...                                                ...
69    2019  http://en.wikipedia.org/wiki/2019_Formula_One_...
70    2020  http://en.wikipedia.org/wiki/2020_Formula_One_...
71    2021  http://en.wikipedia.org/wiki/2021_Formula_One_...
72    2022  http://en.wikipedia.org/wiki/2022_Formula_One_...
73    2023  https://en.wikipedia.org/wiki/2023_Formula_One...

[74 rows x 2 columns]

Lo exportarmos en un archivo csv.

In [24]:
pd.DataFrame(seasons).to_csv('seasons.csv',index=False)

##  Tabla Races

Primero vamos a crear un diccionario llamado races.

In [25]:
races = {'season':[],
        'round':[],
        'raceName' : [],
        'circuitId':[],
        'lat':[],
        'long': [],
        'country':[],
        'date': [],
        'url' : []}

Haremos un for para traernos las carreras del 2010 al 2022

In [26]:
for year in list(range(2010,2023)):
    url = "http://ergast.com/api/f1/{}.json"
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    
    #Vamos a ir iterando para cada una de las carreras.
    #Para cada uno de los elementos de la lista de la carrera
    for item in content['MRData']['RaceTable']['Races']:
        races["season"].append(int(item["season"]))  # Lo convertimos a entero de una vez
        races["round"].append(int(item["round"]))
        races["raceName"].append(item["raceName"])
        races["circuitId"].append(item["Circuit"]["circuitId"])
        races["lat"].append(item["Circuit"]["Location"]["lat"])
        races["long"].append(item["Circuit"]["Location"]["long"])
        races["country"].append(item["Circuit"]["Location"]["country"])
        races["date"].append(item["date"])
        races["url"].append(item["url"])

## Data Frame Races

In [27]:
pd.DataFrame(races)

,season,round,raceName,circuitId,lat,long,country,date,url
0,2010,1,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2010-03-14,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...
1,2010,2,Australian Grand Prix,albert_park,-37.8497,144.968,Australia,2010-03-28,http://en.wikipedia.org/wiki/2010_Australian_G...
2,2010,3,Malaysian Grand Prix,sepang,2.76083,101.738,Malaysia,2010-04-04,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...
3,2010,4,Chinese Grand Prix,shanghai,31.3389,121.22,China,2010-04-18,http://en.wikipedia.org/wiki/2010_Chinese_Gran...
4,2010,5,Spanish Grand Prix,catalunya,41.57,2.26111,Spain,2010-05-09,http://en.wikipedia.org/wiki/2010_Spanish_Gran...
...,...,...,...,...,...,...,...,...,...
254,2022,18,Japanese Grand Prix,suzuka,34.8431,136.541,Japan,2022-10-09,http://en.wikipedia.org/wiki/2022_Japanese_Gra...
255,2022,19,United States Grand Prix,americas,30.1328,-97.6411,USA,2022-10-23,http://en.wikipedia.org/wiki/2022_United_State...
256,2022,20,Mexico City Grand Prix,rodriguez,19.4042,-99.0907,Mexico,2022-10-30,http://en.wikipedia.org/wiki/2022_Mexican_Gran...
257,2022,21,Brazilian Grand Prix,interlagos,-23.7036,-46.6997,Brazil,2022-11-13,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...
258,2022,22,Abu Dhabi Grand Prix,yas_marina,24.4672,54.6031,UAE,2022-11-20,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...

Lo exportarmos en un archivo csv.

In [29]:
pd.DataFrame(races).to_csv('races.csv',index=False)

## TABLA SPRINT RESULTS

Veremos un resumen de  los datos de 2010 a 2022. Primero haremos nuestro diccionario de listas, llamado Sp.

In [30]:
Sp = {"year":[],
    "driverId":[],
   "constructorId" : [],
    "number" : [],
    "grid" :[],
    "position" :[],
    "PositionText" : [],
    #"PositionOrder" : [],
    "points":[],
    "laps" : [],
    "time" : [],
    "milliseconds" :[],
    "fastestLap" : [],
    "fastestLapTime" : [],
    "statusid" : []}

Ahora, haremos nuestro ciclo for para los años de  2010 a 2023, en este trabajaremos con el rango de años de 2021 a 2023.

In [31]:
for year in list(range(2021,2023)):
    url = "http://ergast.com/api/f1/{}/sprint.json"
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    
     
    for item in content["MRData"]["RaceTable"]['Races'][0]['SprintResults']:
        Sp["year"].append(year)
        try:
            Sp["driverId"].append(item["Driver"]["driverId"])
        except : 
            Sp["driverId"].append(None)
        try:    
            Sp["constructorId"].append(item["Constructor"]["constructorId"])
        except:
            Sp["constructorId"].append(None)
        try:
            Sp["number"].append(item["number"])
        except:
            Sp["number"].append(None)
        try:
            Sp["grid"].append(item["grid"])
        except:
            Sp["grid"].append(None)
        try:
            Sp["position"].append(item["position"])
        except:   
            Sp["position"].append(None)
        try:
            Sp["PositionText"].append(item["positionText"])
        except:    
            Sp["PositionText"].append(None)
        #Sp["positionOrder"].append(item["positionOrder"])
        try:
            Sp["points"].append(item["points"]) 
        except:
            Sp["points"].append(None) 
        try:    
            Sp["laps"].append(item["laps"])
        except:
            Sp["laps"].append(None)
        try:    
            Sp["time"].append(item["Time"]["time"]) 
        except: 
            Sp["time"].append(None) 
        try:
            Sp["milliseconds"].append(item["Time"]["millis"])
        except:
            Sp["milliseconds"].append(None)
        try:
            Sp["fastestLap"].append(item["FastestLap"]["lap"])
        except:
            Sp["fastestLap"].append(None)
        try:
            Sp["fastestLapTime"].append(item["FastestLap"]["Time"]["time"])
        except:
            Sp["fastestLapTime"].append(None)
        try:    
            Sp["statusid"].append(item["status"])
        except:
            Sp["statusid"].append(None)

## DATA FRAME SPRINT RESULTS

In [32]:
pd.DataFrame(Sp)

,year,driverId,constructorId,number,grid,position,PositionText,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusid
0,2021,max_verstappen,red_bull,33,2,1,1,3,17,25:38.426,1538426,14,1:30.013,Finished
1,2021,hamilton,mercedes,44,1,2,2,2,17,+1.430,1539856,17,1:29.937,Finished
2,2021,bottas,mercedes,77,3,3,3,1,17,+7.502,1545928,17,1:29.958,Finished
3,2021,leclerc,ferrari,16,4,4,4,0,17,+11.278,1549704,16,1:30.163,Finished
4,2021,norris,mclaren,4,6,5,5,0,17,+24.111,1562537,16,1:30.566,Finished
5,2021,ricciardo,mclaren,3,7,6,6,0,17,+30.959,1569385,17,1:30.640,Finished
6,2021,alonso,alpine,14,11,7,7,0,17,+43.527,1581953,17,1:31.773,Finished
7,2021,vettel,aston_martin,5,10,8,8,0,17,+44.439,1582865,17,1:31.687,Finished
8,2021,russell,williams,63,8,9,9,0,17,+46.652,1585078,17,1:32.208,Finished
9,2021,ocon,alpine,31,13,10,10,0,17,+47.395,1585821,16,1:32.183,Finished
10,2021,sainz,ferrari,55,9,11,11,0,17,+47.798,1586224,10,1:31.991,Finished
11,2021,gasly,alphatauri,10,12,12,12,0,17,+48.763,1587189,17,1:32.072,Finished
12,2021,raikkonen,alfa,7,17,13,13,0,17,+50.677,1589103,12,1:32.139,Finished
13,2021,stroll,aston_martin,18,15,14,14,0,17,+52.179,1590605,12,1:32.210,Finished
14,2021,giovinazzi,alfa,99,14,15,15,0,17,+53.225,1591651,14,1:32.457,Finished
15,2021,tsunoda,alphatauri,22,16,16,16,0,17,+53.567,1591993,14,1:32.270,Finished
16,2021,latifi,williams,6,18,17,17,0,17,+55.162,1593588,17,1:32.143,Finished
17,2021,mick_schumacher,haas,47,19,18,18,0,17,+1:08.213,1606639,15,1:32.567,Finished
18,2021,mazepin,haas,9,20,19,19,0,17,+1:17.648,1616074,3,1:33.462,Finished
19,2021,perez,red_bull,11,5,20,R,0,16,None,None,6,1:31.465,Vibrations
20,2022,max_verstappen,red_bull,1,1,1,1,8,21,30:39.567,1839567,14,1:19.154,Finished
21,2022,leclerc,ferrari,16,2,2,2,7,21,+2.975,1842542,11,1:19.044,Finished
22,2022,perez,red_bull,11,7,3,3,6,21,+4.721,1844288,14,1:19.012,Finished
23,2022,sainz,ferrari,55,10,4,4,5,21,+17.578,1857145,14,1:19.251,Finished
24,2022,norris,mclaren,4,3,5,5,4,21,+24.561,1864128,9,1:20.030,Finished
25,2022,ricciardo,mclaren,3,6,6,6,3,21,+27.740,1867307,12,1:20.328,Finished
26,2022,bottas,alfa,77,8,7,7,2,21,+28.133,1867700,9,1:20.219,Finished
27,2022,kevin_magnussen,haas,20,4,8,8,1,21,+30.712,1870279,6,1:20.557,Finished
28,2022,alonso,alpine,14,5,9,9,0,21,+32.278,1871845,10,1:20.639,Finished
29,2022,mick_schumacher,haas,47,12,10,10,0,21,+33.773,1873340,15,1:20.567,Finished
30,2022,russell,mercedes,63,11,11,11,0,21,+36.284,1875851,19,1:20.756,Finished
31,2022,tsunoda,alphatauri,22,16,12,12,0,21,+38.298,1877865,20,1:20.909,Finished
32,2022,vettel,aston_martin,5,9,13,13,0,21,+40.177,1879744,8,1:21.044,Finished
33,2022,hamilton,mercedes,44,13,14,14,0,21,+41.459,1881026,9,1:20.663,Finished
34,2022,stroll,aston_martin,18,15,15,15,0,21,+42.910,1882477,14,1:20.948,Finished
35,2022,ocon,alpine,31,19,16,16,0,21,+43.517,1883084,14,1:20.995,Finished
36,2022,gasly,alphatauri,10,17,17,17,0,21,+43.794,1883361,18,1:20.599,Finished
37,2022,albon,williams,23,20,18,18,0,21,+48.871,1888438,14,1:21.020,Finished
38,2022,latifi,williams,6,18,19,19,0,21,+52.017,1891584,16,1:21.437,Finished
39,2022,zhou,alfa,24,0,20,R,0,0,None,None,None,None,Retired

Lo exportarmos en un archivo csv.

In [33]:
pd.DataFrame(Sp).to_csv("Sprint Results.csv", index= False)

## TABLA STATUS

Primero haremos nuestro diccionario de listas, llamado ST.

In [34]:
ST ={"year":[],
     "StatusId":[],
    "Status":[],
    "Count":[]}

Analogamente, haremos nuestro ciclo for para los años de  2010 a 2023, en este trabajaremos con el rango de años de 2021 a 2023.

In [35]:
for year in list(range(2010,2023)):
    url = "http://ergast.com/api/f1/{}/status.json"
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content["MRData"]['StatusTable']["Status"]:
        ST["year"].append(year)
        try:
            ST["StatusId"].append(item["statusId"])
        except:
            ST["StatusId"].append(None)
        try:
            ST["Status"].append(item["status"])
        except:
            ST["Status"].append(None)
        try:
            ST["Count"].append(item["count"])
        except:
            ST["Count"].append(None)

## Data frame STATUS

In [36]:
pd.DataFrame(ST)

     year StatusId            Status Count
0    2010        1          Finished   212
1    2010        3          Accident    17
2    2010        4         Collision    25
3    2010        5            Engine    13
4    2010        6           Gearbox     9
..    ...      ...               ...   ...
356  2022      103        Water pump     1
357  2022      130  Collision damage    12
358  2022      131        Power Unit     6
359  2022      140         Undertray     2
360  2022      141    Cooling system     1

[361 rows x 4 columns]

Ahora lo vamos a convertir a un archivo  Csv

In [37]:
pd.DataFrame(ST).to_csv("Status.csv",index = False)

## TABLA RESULTS

Ahora veamos nuestra tabla de Results

In [38]:
RS = {"year":[],
    "driverId":[],
   "constructorId" : [],
    "number" : [],
    "grid" :[],
    "position" :[],
    "PositionText" : [],
    #"PositionOrder" : [],
    "points":[],
    "laps" : [],
    "time" : [],
    "milliseconds" :[],
    "fastestLap" : [],
      "Rank":[],
      "fastestLapTime" : [],
    "fastestLapSpeed" : [],
    "statusid" : []}

In [37]:
for year in list(range(2010,2023)):
    url = "http://ergast.com/api/f1/{}/results.json"
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    
    for item in content["MRData"]["RaceTable"]["Races"][0]["Results"]:
        RS["year"].append(year)
        try:
            RS["driverId"].append(item["Driver"]["driverId"])
        except : 
            RS["driverId"].append(None)
        try:    
            RS["constructorId"].append(item["Constructor"]["constructorId"])
        except:
            RS["constructorId"].append(None)
        try:
            RS["number"].append(item["number"])
        except:
            RS["number"].append(None)
        try:
            RS["grid"].append(item["grid"])
        except:
            RS["grid"].append(None)
        try:
            RS["position"].append(item["position"])
        except:   
            RS["position"].append(None)
        try:
            RS["PositionText"].append(item["positionText"])
        except:    
            RS["PositionText"].append(None)
        #Sp["positionOrder"].append(item["positionOrder"])
        try:
            RS["points"].append(item["points"]) 
        except:
            RS["points"].append(None) 
        try:    
            RS["laps"].append(item["laps"])
        except:
            RS["laps"].append(None)
        try:    
            RS["time"].append(item["Time"]["time"]) 
        except: 
            RS["time"].append(None) 
        try:
            RS["milliseconds"].append(item["Time"]["millis"])
        except:
            RS["milliseconds"].append(None)
        try:
            RS["fastestLap"].append(item["FastestLap"]["lap"])
        except:
            RS["fastestLap"].append(None)
        try:
            RS["Rank"].append(item["FastestLap"]["rank"])
        except:
            RS["Rank"].append(None)
        try:
            RS["fastestLapTime"].append(item["FastestLap"]["Time"]["time"])
        except:
            RS["fastestLapTime"].append(None)
        try:
            RS["fastestLapSpeed"].append(item["FastestLap"]["Time"]["time"])
        except:
            RS["fastestLapSpeed"].append(None)
        try:    
            RS["statusid"].append(item["status"])
        except:
            RS["statusid"].append(None)

## Data Frame Results

In [39]:
pd.DataFrame(RS)

Empty DataFrame
Columns: [year, driverId, constructorId, number, grid, position, PositionText, points, laps, time, milliseconds, fastestLap, Rank, fastestLapTime, fastestLapSpeed, statusid]
Index: []

Ahora lo guardaremos como un archivo csv

In [40]:
pd.DataFrame(RS).to_csv("Results.csv", index= False)

## TABLA PITSTOPS

Primero haremos nuestro diccionario de listas, llamado PS.

In [41]:
PS = {"year" : [],
      "round":[],
    "driverId":[],
     "stop":[],
     "lap":[],
     "time":[],
      "duration":[],
      #"milliseconds":[]
     }

Ahora haremos varios for iterados para crear las rondas.

In [42]:
for n  in list(range(1,12)):
    ronda = n
    
    for year in list(range(2011,2023)):
        #n = 1 
        url = f"http://ergast.com/api/f1/{year}/{ronda}/pitstops.json"
        response = requests.get(url)
        content=json.loads(response.content)
        
        for item in content["MRData"]["RaceTable"]["Races"][0]["PitStops"]:
            PS["year"].append(year)
            PS["round"].append(n)
            try:
                PS["driverId"].append(item["driverId"])
            except:
                PS["driverId"].append(None)
            try:
                PS["lap"].append(item["lap"])
            except:
                PS["lap"].append(None)
            try:
                PS["stop"].append(item["stop"])
            except:
                PS["stop"].append(None)  
            try:
                PS["time"].append(item["time"])
            except:
                PS["time"].append(None)
            try:
                PS["duration"].append(item["duration"])
            except:
                PS["duration"].append(None)

In [42]:
for n  in list(range(14,18)):
    ronda = n
    
    for year in list(range(2011,2023)):
        #n = 1 
        url = f"http://ergast.com/api/f1/{year}/{ronda}/pitstops.json"
        response = requests.get(url)
        content=json.loads(response.content)
        #for n in len(content["MRData"]["RaceTable"]["round"]):

        for item in content["MRData"]["RaceTable"]["Races"][0]["PitStops"]:
            PS["year"].append(year)
            PS["round"].append(n)
            try:
                PS["driverId"].append(item["driverId"])
            except:
                PS["driverId"].append(None)
            try:
                PS["lap"].append(item["lap"])
            except:
                PS["lap"].append(None)
            try:
                PS["stop"].append(item["stop"])
            except:
                PS["stop"].append(None)  
            try:
                PS["time"].append(item["time"])
            except:
                PS["time"].append(None)
            try:
                PS["duration"].append(item["duration"])
            except:
                PS["duration"].append(None)

##  DATA FRAME PITSTOPS

In [43]:
pd.DataFrame(PS)

      year  round            driverId stop lap      time duration
0     2011      1         alguersuari    1   1  17:05:23   26.898
1     2011      1  michael_schumacher    1   1  17:05:52   25.021
2     2011      1              webber    1  11  17:20:48   23.426
3     2011      1              alonso    1  12  17:22:34   23.251
4     2011      1               massa    1  13  17:24:10   23.842
...    ...    ...                 ...  ...  ..       ...      ...
3668  2022     11     kevin_magnussen    2  41  15:52:37   22.088
3669  2022     11               albon    2  41  15:52:47   22.122
3670  2022     11     mick_schumacher    2  43  15:54:56   22.880
3671  2022     11              norris    2  43  15:55:00   27.324
3672  2022     11                ocon    2  44  15:56:05   22.109

[3673 rows x 7 columns]

Ahora lo guardaremos como un archivo csv

In [44]:
pd.DataFrame(PS).to_csv("PitStops.csv", index = False)

## TABLA LAP TIMES

Primero haremos nuestro diccionario de listas, llamado LP.

In [45]:
LP={"year":[],
    "round":[],
    "driverId":[],
   "lap":[],
   "position":[],
   "time":[]}
  # "milliseconds":[]}

Ahora haremos varios for iterados para obtener el tiempo de cada carrera y para cada ronda.

In [ ]:
for n  in list(range(1,12)):
    ronda = n

    for year in list(range(2010,2023)):
        for k in list(range(1,30)):  
            url = f"http://ergast.com/api/f1/{year}/{ronda}/laps/{k}.json"
            response = requests.get(url)
            content=json.loads(response.content)

            for item in content["MRData"]["RaceTable"]["Races"][0]["Laps"]:
                LP["year"].append(year)
                LP["round"].append(n)
                try:
                    LP["driverId"].append(item["Timings"][0]["driverId"])
                except:
                    LP["driverId"].append(None)
                try:
                    LP["position"].append(item["Timings"][0]["position"])
                except:
                    LP["position"].append(None)
                try:
                    LP["time"].append(item["Timings"][0]["time"])
                except:
                    LP["time"].append(None)
                try:
                    LP["lap"].append(item["number"])
                except:
                    LP["lap"].append(None)
    
for n  in list(range(14,18)):
    ronda = n

    for year in list(range(2010,2023)):
        for k in list(range(1,30)):  
            url = f"http://ergast.com/api/f1/{year}/{ronda}/laps/{k}.json"
            response = requests.get(url)
            content=json.loads(response.content)

            for item in content["MRData"]["RaceTable"]["Races"][0]["Laps"]:
                LP["year"].append(year)
                LP["round"].append(n)
                try:
                    LP["driverId"].append(item["Timings"][0]["driverId"])
                except:
                    LP["driverId"].append(None)
                try:
                    LP["position"].append(item["Timings"][0]["position"])
                except:
                    LP["position"].append(None)
                try:
                    LP["time"].append(item["Timings"][0]["time"])
                except:
                    LP["time"].append(None)
                try:
                    LP["lap"].append(item["number"])
                except:
                    LP["lap"].append(None)

## DATA FRAME LAP TIMES

In [ ]:
pd.DataFrame(LP)

Ahora lo vamos a convertir a un archivo  Csv

In [ ]:
pd.DataFrame(LP).to_csv("Lap Time.csv", index = False)

## TABLA DRIVER STANDINGS

Primero haremos un diccionario de nuestras listas y note que como no todos los datos tienen el mismo número de rondas, solo se haran 17 rondas.

In [ ]:
DS={"year":[],
    "round":[],
    "driverId":[],
   "points":[],
   "position":[],
   "positionText":[],
   "Wins":[]}

In [ ]:
for n  in list(range(1,18)):
    ronda = n
    
    for year in list(range(2010,2023)):
        url = f"http://ergast.com/api/f1/{year}/{ronda}/driverStandings.json"
        response = requests.get(url)
        content=json.loads(response.content)
        
        for item in content["MRData"]["StandingsTable"]["StandingsLists"][0]["DriverStandings"]:
            DS["year"].append(year)
            DS["round"].append(n)
            try:
                DS["driverId"].append(item["Driver"]["driverId"])
            except:
                DS["driverId"].append(None)
            try:
                DS["points"].append(item["points"])
            except:
                DS["points"].append(None)
            try:
                DS["position"].append(item["position"])
            except:
                DS["position"].append(None)  
            try:
                DS["positionText"].append(item["positionText"])
            except:
                DS["positionText"].append(None)
            try:
                DS["Wins"].append(item["wins"])
            except:
                DS["Wins"].append(None)

## DATAFRAME DRIVER STANDINGS

In [ ]:
pd.DataFrame(DS)

Luego lo vamos a exportar en un archivo csv.

In [ ]:
pd.DataFrame(DS).to_csv("DriverStandings.csv", index= False )

## TABLA CONSTRUCTOR STANDINGS

Primero haremos nuestro diccionario de listas, llamado CS.

In [ ]:
CS={"year":[],
    "round":[],
    "ConstructorId":[],
   "points":[],
   "position":[],
   "positionText":[],
   "Wins":[]}

In [ ]:
for n  in list(range(1,18)):
    ronda = n
    
    for year in list(range(2010,2023)):
        url = f"http://ergast.com/api/f1/{year}/{ronda}/constructorStandings.json"
        response = requests.get(url)
        content=json.loads(response.content)
        
        for item in content["MRData"]["StandingsTable"]["StandingsLists"][0]["ConstructorStandings"]:
            CS["year"].append(year)
            CS["round"].append(n)
            try:
                CS["ConstructorId"].append(item["Constructor"]["constructorId"])
            except:
                CS["ConstructorId"].append(None)
            try:
                CS["points"].append(item["points"])
            except:
                CS["points"].append(None)
            try:
                CS["position"].append(item["position"])
            except:
                CS["position"].append(None)  
            try:
                CS["positionText"].append(item["positionText"])
            except:
                CS["positionText"].append(None)
            try:
                CS["Wins"].append(item["wins"])
            except:
                CS["Wins"].append(None)

## DATAFRAME CONSTRUCTOR STANDINGS

In [ ]:
pd.DataFrame(CS)

Luego lo vamos a exportar en un archivo csv.

In [ ]:
pd.DataFrame(CS).to_csv("ConstructorStandings.csv", index= False)

## TABLA CONSTRUCTOR RESULTS

En esta tabla pondremos los datos del primero en llegar es decir de cada vuelta en cada ronda 
lo estaremos obteniendo solo de la primera persona en llegar

In [ ]:
CR ={"year":[],
     "round":[],
    "ConstructorId":[],
   "points":[],
     "status":[]}

In [ ]:
for n  in list(range(1,18)):
    ronda = n
    
    for year in list(range(2010,2023)):
        url = f"http://ergast.com/api/f1/{year}/{ronda}/results.json"
        response = requests.get(url)
        content=json.loads(response.content)
    
        for item in content["MRData"]["RaceTable"]["Races"][0]["Results"]:
            CR["year"].append(year)
            CR["round"].append(n)
            try:    
                CR["ConstructorId"].append(item["Constructor"]["constructorId"])
            except:
                CR["ConstructorId"].append(None)
            try:
                CR["points"].append(item["points"])
            except:
                CR["points"].append(None)
            try:
                CR["status"].append(item["status"])
            except:
                CR["status"].append(None)

In [ ]:
pd.DataFrame(CR)

In [ ]:
pd.DataFrame(CR).to_csv("ConstructorResults.csv", index= False)

En el caso de que quiera la suma de los puntos totales lo hacemos como:

In [ ]:
df=pd.DataFrame(CR)
df["points"] = df["points"].astype(float)
df1 = df.groupby(["ConstructorId"]).agg({"points": "sum"}).sort_values(by = "points", ascending = False )
df1

Luego lo vamos a exportar en un archivo csv.

In [ ]:
df1.to_csv("ConstructorResults(suma).csv", index = True)